\context ChordNames \chords {
	% intro
	\skip 1*2

	% Santo, santo, santo...
	\break
	\skip 1*4 \break
	\skip 1*4

	% Santo, santo, santo...
	\break
	\skip 1*4 \break
	\skip 1*4

	% Llenos estan el cielo y la tierra...
	\break
	\skip 1*4
	\skip 1*4

	% Bendito el que viene...
	\break
	\skip 1*4
	\skip 1*4

	% Santo, santo, santo...
	\break
	\skip 1*4 \break
	\skip 1*4

	% Santo, santo, santo...
	\break
	\skip 1*4 \break
	\skip 1*4
	%\skip 1*2
}
